# Generated by Django 4.2.7 on 2025-05-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('detailed_description', models.TextField(verbose_name='Batafsil tavsif')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Rasm')),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], max_length=20, verbose_name='Qiyinchilik darajasi')),
                ('duration', models.CharField(max_length=50, verbose_name='Davomiylik')),
                ('schedule', models.CharField(max_length=100, verbose_name='Jadval')),
                ('start_date', models.CharField(max_length=50, verbose_name='Boshlanish sanasi')),
                ('max_students', models.PositiveIntegerField(verbose_name='Maksimal talabalar soni')),
                ('price', models.CharField(max_length=50, verbose_name='Narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(verbose_name='Hafta')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_items', to='api.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs dasturi',
                'verbose_name_plural': 'Kurs dasturlari',
                'ordering': ['course', 'week'],
                'unique_together': {('course', 'week')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('content', models.TextField(blank=True, verbose_name='Mazmun')),
                ('image', models.ImageField(blank=True, upload_to='resources/', verbose_name='Rasm')),
                ('category', models.CharField(choices=[('tutorials', "Qo'llanmalar"), ('videos', 'Videolar'), ('books', 'Kitoblar'), ('downloads', 'Yuklamalar')], max_length=20, verbose_name='Kategoriya')),
                ('file', models.FileField(blank=True, upload_to='resources/files/', verbose_name='Fayl')),
                ('external_link', models.URLField(blank=True, verbose_name='Tashqi havola')),
                ('is_external', models.BooleanField(default=False, verbose_name='Tashqi manba')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='Yuklab olinadimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(max_length=50, verbose_name='Ikonka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('detailed_description', models.TextField(verbose_name='Batafsil tavsif')),
                ('points', models.PositiveIntegerField(verbose_name='Ballar')),
                ('estimated_time', models.CharField(max_length=50, verbose_name='Taxminiy vaqt')),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], max_length=20, verbose_name='Qiyinchilik darajasi')),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='not_started', max_length=20, verbose_name='Holat')),
                ('sample_code', models.TextField(blank=True, verbose_name='Namuna kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.course', verbose_name="Bog'liq kurs")),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('content', models.TextField(verbose_name='Izoh')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255, verbose_name='Talab')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa talabi',
                'verbose_name_plural': 'Vazifa talablari',
            },
        ),
        migrations.CreateModel(
            name='TaskHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField(verbose_name='Maslahat')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa maslahati',
                'verbose_name_plural': 'Vazifa maslahatlari',
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.coursesyllabus', verbose_name='Kurs dasturi')),
            ],
            options={
                'verbose_name': 'Kurs mavzusi',
                'verbose_name_plural': 'Kurs mavzulari',
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Qadam raqami')),
                ('title', models.CharField(max_length=200, verbose_name='Qadam nomi')),
                ('description', models.TextField(verbose_name='Qadam tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_steps/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.project')),
            ],
            options={
                'verbose_name': 'Loyiha qadami',
                'verbose_name_plural': 'Loyiha qadamlari',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Material nomi')),
                ('description', models.TextField(verbose_name='Material tavsifi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('unit', models.CharField(max_length=50, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.project')),
            ],
            options={
                'verbose_name': 'Loyiha materialii',
                'verbose_name_plural': 'Loyiha materiallari',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('title', models.CharField(max_length=255, verbose_name='Unvon')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('photo', models.ImageField(upload_to='instructors/', verbose_name='Rasm')),
                ('courses', models.ManyToManyField(related_name='instructors', to='api.course', verbose_name='Kurslar')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('comments', models.TextField(blank=True, verbose_name='Izohlar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': "Ro'yxatdan o'tish",
                'verbose_name_plural': "Ro'yxatdan o'tishlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
