# Generated by Django 4.2.7 on 2025-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default=2, max_length=20, verbose_name='Qiyinchilik darajasi'),
            preserve_default=False,
        ),
    ]
