# Generated by Django 4.2.7 on 2025-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample_code',
            field=models.TextField(blank=True, verbose_name='Namuna kod'),
        ),
    ]
