# Generated by Django 4.2.7 on 2025-05-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_sample_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_code',
            field=models.TextField(blank=True, null=True, verbose_name='Namuna kod'),
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('code', models.TextField(verbose_name='Yechim kodi')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa yechimi',
                'verbose_name_plural': 'Vazifa yechimlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
